server:
  port: 8020
spring:
  datasource:
    url:jdbc:mysql://localhost:3306/order?useUnicode=true&character=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone:http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
